correcoes no atualizador

diff --git a/Atual/baixarAtualizacao b/Atual/baixarAtualizacao
--- a/Atual/baixarAtualizacao
+++ b/Atual/baixarAtualizacao
@@ -20,7 +20,7 @@ MENSAGEM_USO="
 Programa: $(basename "$0")
 
 --------------------------------------------------------------------------------
-                              [OPCOES DISPONIVEIS]
+                            [OPCOES DISPONIVEIS]
 
 OPCOES NA LINHA DE COMANDO:
     -h, --help      Mostra esta tela de ajuda e sai
@@ -36,7 +36,7 @@ URL_BASE_VERSAO40="https://s3.amazonaws.com/avancoprogramas/integral/versao40-"
 URL_BASE_VERSAO41="https://s3.amazonaws.com/avancoprogramas/integral/versao41-"
 
 URL_BASE_RELEASE40="https://s3.amazonaws.com/avancoprogramas/integral/release40-"
-URL_BASE_RELEASE41="https://s3.amazonaws.com/avancoprogramas/integral/release41-"
+URL_BASE_RELEASE41="https://s3.amazonaws.com/avancoprogramas/integral/release-"
 
 URL_ATUALIZADOV40=""
 URL_ATUALIZADOV41=""
@@ -54,6 +54,8 @@ data_release=""
 cobolBusca=""
 
 release_busca=""
+releaseBusca=""
+letraRelease=""
 
 PASTA_DESTINO="/u/rede/avanco/atualizacoes"
 
@@ -61,10 +63,10 @@ infos_extras="/u/sist/logs/infos_extras.log"
 
 SCRIPT_PATH="$0"
 SCRIPT_URL="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/baixarAtualizacao"
-URL_CONTROLE_VERSAO_RELEASE="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/controle_ver_rel.txt"
+url_versao_release="https://raw.githubusercontent.com/ketteiGustavo/atualizador/main/Atual/versao_release.txt"
 
 data_atual=$(date +%Y%m%d)
-#data_atual="20240718"
+
 
 atualizado_flag=""
 controle_flag="/u/sist/controle"
@@ -84,8 +86,7 @@ mostrar_versao() {
 }
 
 
-
-arquivo="/u/sist/controle/controle_ver_rel.txt"
+controle_ver_rel="/u/sist/controle/versao_release.txt"
 
 # Funcao para verificar qual o cobol usado
 VERIFICA_COBOL() {
@@ -111,66 +112,18 @@ TRATAR_DATAS () {
 
 # Função para ler o arquivo e armazenar as informações em variáveis
 ler_arquivo() {
-    local arquivo="/u/sist/controle/controle_ver_rel.txt"
     local versao
-    local lendo_atualizado
-    declare -A releases
-
-    while IFS= read -r linha; do
-        if [[ "$linha" =~ ^Informacoes\ atualizadas\ em:\ ([0-9]+)$ ]]; then
-            lendo_atualizado="${BASH_REMATCH[1]}"
-        elif [[ "$linha" =~ ^Versao\ disponivel\ no\ portal:\ ([0-9]+)$ ]]; then
-            versao="${BASH_REMATCH[1]}"
-        elif [[ "$linha" =~ ^RELEASE\ ([A-Z])\ -\ DATA:\ ([0-9]+)$ ]]; then
-            releases["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
-        fi
-    done < "$arquivo"
-
-    data_atualizada=$(TRATAR_DATAS "$lendo_atualizado")
-    echo ""
-    echo "INFORMACOES ATUALIZADAS EM: $data_atualizada"
-    echo ""
-    data_exibicao=$(TRATAR_DATAS "$versao")
-    echo "VERSAO DISPONIVEL NO PORTAL: $data_exibicao"
+    local arquivo="$controle_ver_rel"
+    versao=$(grep -oP '(?<=Versao atual: )\d+' "$arquivo")
     versao_Portal="$versao"
-    
+    echo "Versao: $versao_Portal"
     echo "$versao" > "/u/sist/controle/versaoIntegral"
-    for release in "${!releases[@]}"; do
-        
-        echo "RELEASE $release - DATA: ${releases[$release]}" > /dev/null
-    done
-    
-    # Verificar a release disponível de acordo com a data atual
-    verificar_release_disponivel "$versao" releases
-}
-
-# Função para converter data no formato DDMMYY para YYYY-MM-DD
-converter_data() {
-    local data="$1"
-    echo "20${data:4:2}-${data:2:2}-${data:0:2}"
-}
-
-# Função para verificar a release disponível de acordo com a data atual
-verificar_release_disponivel() {
-    local versao="$1"
-    declare -n releases_ref="$2"
-
-    #echo "mostrando data de hoje: $data_atual"
-
-    for release in "${!releases_ref[@]}"; do
-        local data_release="${releases_ref[$release]}"
-        local data_release_yyyymmdd=$(date -d "$(converter_data "$data_release")" +%Y%m%d)
-
-        if [[ "$data_atual" -ge "$data_release_yyyymmdd" ]]; then
-            release_formatada=$(TRATAR_DATAS "$data_release")
-            echo "RELEASE DISPONIVEL NO PORTAL: $release - DATA: $release_formatada"
-            echo "$release" > "/u/sist/controle/releaseIntegral"
-            echo "$data_release" > "/u/sist/controle/dataReleaseIntegral"
-            return
-        fi
-    done
-
-    echo "RELEASE ESTARA DISPONIVEL NOS PROXIMOS DIAS!"
+    release_busca=$(grep -oP '(?<=Release atual: [A-Z] )\d{6}' "$arquivo")
+    data_release="$release_busca"
+    echo "Data da release: $data_release"
+    echo "$data_release" > "/u/sist/controle/dataReleaseIntegral"
+    release=$(grep -oP '(?<=Release atual: )[A-Z]' "$arquivo")
+    echo "$release" > "/u/sist/controle/releaseIntegral"
 }
 
 # Funcao para converter datas no formato YYYYMMDD, para ser usado em equacoes de comparacao, maior, menor e igual
@@ -240,25 +193,15 @@ BAIXAR_RELEASE() {
     VERIFICA_COBOL
     arquivo_release_atual=""
     buscarV40="release40"
-    buscarV41="release41"
-    releaseBusca=""
+    buscarV41="release"
 
-    if [ -f "/u/sist/controle/dataReleaseIntegral" ] && [ -s "/u/sist/controle/dataReleaseIntegral" ]; then
-        release_busca=$(cat "/u/sist/controle/dataReleaseIntegral")
-    else
-        release_busca=""
-    fi
-    if [ -f "/u/sist/controle/versaoIntegral" ] && [ -s "/u/sist/controle/versaoIntegral" ]; then
-        versao_busca=$(cat "/u/sist/controle/versaoIntegral")
-    fi
-
-    #echo "arquivo txt release: $release_busca"
-    #echo "arquivo txt versao : $versao_busca"
+    echo "arquivo txt release: $release_busca"
+    echo "arquivo txt versao : $versao_busca"
     local rel="${release_busca:0:4}"
-    local ver="${versao_busca:0:4}"
+    local ver="${versao_Portal:0:4}"
     
-    #echo "tratada versao: $ver"
-    #echo "tratada release: $rel"
+    echo "tratada versao: $ver"
+    echo "tratada release: $rel"
     
 
     # Verificando a versao do COBOL
@@ -276,6 +219,7 @@ BAIXAR_RELEASE() {
     fi
 
     URL_ATUALIZADO_RELEASE="$URL_BUSCAR_RELEASE$ver-a-$rel.rar"
+    echo "URL: $URL_ATUALIZADO_RELEASE"
     if curl --output /dev/null --silent --head --fail "$URL_ATUALIZADO_RELEASE"; then
         wget -c --progress=dot "$URL_ATUALIZADO_RELEASE" -P "$PASTA_DESTINO" 2>&1 | \
         grep --line-buffered "%" | \
@@ -295,10 +239,10 @@ BAIXAR_RELEASE() {
         done
         then
             release_download=$(TRATAR_DATAS "$release_busca")
-            echo "DOWNLOAD DA RELEASE '$letra_release_atual, DO DIA $release_download' CONCLUIDO E PROGRAMAS 'TESTADOS'!!"
+            echo "DOWNLOAD DA RELEASE '$release, DO DIA $release_download' CONCLUIDO E PROGRAMAS 'TESTADOS'!!"
         else
             echo "Arquivo corrompido!"
-            echo "Arquivo de release '$release_download - $letra_release_atual' corrompido!"
+            echo "Arquivo de release '$release_download - $release' corrompido!"
         fi
 
         echo "PACOTE DE ATUALIZACAO BAIXADO!"
@@ -307,72 +251,6 @@ BAIXAR_RELEASE() {
     sleep 1
 }
 
-# Funcao para validar versao e release no cliente e baixar somente o necessario
-VALIDAR_VERSAO_RELEASE () {
-    atualizado_flag=false
-    local data_versao_comparar=$(CONVERTER_DATAS "$versao_Portal")
-    local letra_release_atual="$release"
-    local calculo_data=$(date -d "${data_versao_comparar} +6 days" +"%Y%m%d")
-    local calculo_data_limite=$(date -d "${data_versao_comparar} +3 months" +"%Y%m%d")
-    #echo "1: $calculo_data"
-    #echo "2: $calculo_data_limite"
-    #echo "3: $data_versao_comparar"
-
-    versao_informada=$(cat "/u/sist/controle/inf_versaoLoja.txt") 2> /dev/null
-    letra_informada=$(cat "/u/sist/controle/inf_releaseLoja.txt") 2> /dev/null
-
-    #read -p "LER VERSAO: " versao_informada
-
-    local data_informada_comparar=$(CONVERTER_DATAS "$versao_informada")
-    #echo "$data_informada_comparar"
-    if [ "$data_informada_comparar" -gt "$calculo_data" ] && [ $data_informada_comparar -lt $calculo_data_limite ]; then
-        echo "A RELEASE ATUAL E: $letra_release_atual" > /dev/null
-    fi
-    #read -p "LER RELEASE: " letra_informada
-    letra_informada=$(echo "$letra_informada" | tr '[:lower:]' '[:upper:]')
-
-    #echo "voce informou: $letra_informada"
-    if [[ "$letra_informada" > "M" ]]; then
-        echo "RELEASE INVALIDA"
-    fi
-
-    if [ "$data_informada_comparar" -lt "$data_versao_comparar" ]; then
-        echo "INICIANDO DOWNLOAD..."
-        BAIXAR_VERSAO
-        BAIXAR_RELEASE
-        atualizado_flag=false
-        echo "$atualizado_flag" > $controle_flag/controle_flag.txt
-    elif [ "$data_informada_comparar" -eq "$data_versao_comparar" ]; then
-        echo "INTEGRAL ESTA COM A VERSAO ATUAL!"
-        atualizado_flag=true
-        echo "$atualizado_flag" > $controle_flag/controle_flag.txt
-        #echo "$data_atual"
-        if [ "$data_atual" -gt "$calculo_data" ]; then
-            echo "A RELEASE ATUAL E: $letra_release_atual" > /dev/null
-            if [[ "$letra_informada" < "$letra_release_atual" ]]; then
-                echo "BAIXANDO RELEASE..."
-                BAIXAR_RELEASE
-                atualizado_flag=false
-                echo "$atualizado_flag" > $controle_flag/controle_flag.txt
-            elif [[ "$letra_informada" == "$letra_release_atual" ]]; then
-                echo "INTEGRAL ESTA COM A RELEASE ATUAL!"
-                atualizado_flag=true
-                echo "$atualizado_flag" > $controle_flag/controle_flag.txt
-            else
-                echo "RELEASE INVALIDA!"
-            fi
-        
-        fi
-
-
-            
-    else
-        echo "VERSAO INVALIDA!"
-    fi
-
-    echo "status flag: $atualizado_flag" > /dev/null
-    echo "$atualizado_flag" > $controle_flag/controle_flag.txt
-}
 
 # Funcao para atualizar o script sempre para a versao mais recente
 UPDATE () {
@@ -399,17 +277,27 @@ UPDATE () {
 
 # Funcao para baixar arquivo atualizado
 BAIXAR_CONTROLE () {
-    echo "OBTENDO VERSAO E RELEASE"
-    curl -o "$arquivo.tmp" "$URL_CONTROLE_VERSAO_RELEASE" || wget -ocq "$arquivo.tmp" "$URL_CONTROLE_VERSAO_RELEASE"
+    #echo "OBTENDO VERSAO E RELEASE"
+    if curl --output /dev/null --silent --head --fail "$url_versao_release"; then
+        wget -qcO "$controle_ver_rel.tmp" "$url_versao_release"
 
-    if [ $? -eq 0 ]; then
-        mv "$arquivo.tmp" "$arquivo"
-        chmod 766 "$arquivo"
-        clear
-        echo "DETALHES DE VERSAO E RELEASE OBTIDOS!"
+        if [ $? -eq 0 ]; then
+            mv "$controle_ver_rel.tmp" "$controle_ver_rel"
+            chmod 777 "$controle_ver_rel"
+            clear
+            #echo "DETALHES DE VERSAO E RELEASE OBTIDOS!"
+            novoPortal=$(grep -oP '(?<=Versao atual: )\d+' "$controle_ver_rel")
+            letraRelease=$(grep -oP '(?<=Release atual: )[A-Z]' "$controle_ver_rel")
+            data_release=$(grep -oP '(?<=Release atual: [A-Z] )\d{6}' "$controle_ver_rel")
+            #echo "VERSAO ATUAL: $novoPortal"
+            #echo "RELEASE ATUAL: $data_release - $letraRelease"
+        else
+            echo "ERRO AO OBTER VERSAO E RELEASE RECENTES!"
+            rm -f "$controle_ver_rel.tmp"
+        fi
     else
-        echo "ERRO AO OBTER VERSAO E RELEASE RECENTES!"
-        rm -f "$arquivo.tmp"
+        echo "ERROR: NAO FOI POSSIVEL OBTER AS INFORMACOES DE VERSAO E RELEASE."
+        rm -f "$controle_ver_rel.tmp"
     fi
 }
 
@@ -442,6 +330,18 @@ case "$1" in
     ler_arquivo
     exit 0
     ;;
+--baixarVersao)
+    BAIXAR_CONTROLE
+    ler_arquivo
+    BAIXAR_VERSAO
+    exit 0
+    ;;
+--baixarRelease)
+    BAIXAR_CONTROLE
+    ler_arquivo
+    BAIXAR_RELEASE
+    exit 0
+    ;;
 *)
     if test -n "$1"; then
         echo Opcao invalida: $1
@@ -457,5 +357,4 @@ esac
 clear
 BAIXAR_CONTROLE
 ler_arquivo
-VALIDAR_VERSAO_RELEASE
-UPDATE > /dev/null
+#UPDATE > /dev/null
